insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(531, 41, "기본 재료", "쇠고기등심", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(532, 41, "기본 재료", "두부", "1/3", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(533, 41, "기본 재료", "실곤약", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(534, 41, "기본 재료", "표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(535, 41, "기본 재료", "배추", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(536, 41, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(537, 41, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(538, 41, "기본 재료", "쑥갓", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(539, 41, "기본 재료", "다시마육수", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(540, 41, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(541, 41, "기본 재료", "우동면", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(542, 41, "국물", "맛술", "2/3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(543, 41, "국물", "간장", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(544, 41, "국물", "청주", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(545, 41, "국물", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(546, 42, "기본 재료", "다시마", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(547, 42, "기본 재료", "가쓰오부시", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(548, 42, "기본 재료", "가쓰오 다시", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(549, 42, "기본 재료", "정종", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(550, 42, "기본 재료", "미림", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(551, 42, "기본 재료", "건미역", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(552, 42, "기본 재료", "연두부", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(553, 42, "기본 재료", "팽이버섯", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(554, 42, "미소시루 베이스", "된장", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(555, 42, "미소시루 베이스", "일본 미소시루용 된장", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(556, 42, "미소시루 베이스", "정종", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(557, 42, "미소시루 베이스", "미림", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(558, 43, "기본 재료", "옥도미", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(559, 43, "기본 재료", "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(560, 43, "기본 재료", "구운 대파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(561, 43, "기본 재료", "유자 껍질", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(562, 43, "육수", "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(563, 43, "육수", "정종", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(564, 43, "육수", "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(565, 43, "육수", "소금", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(566, 44, "기본 재료", "모듬어묵", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(567, 44, "기본 재료", "곤약", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(568, 44, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(569, 44, "기본 재료", "마늘", "1", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(570, 44, "기본 재료", "무", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(571, 44, "기본 재료", "건고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(572, 44, "기본 재료", "연겨자", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(573, 44, "기본 재료", "삶은 달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(574, 44, "다시마물", "물", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(575, 44, "다시마물", "멸치", "10", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(576, 44, "다시마물", "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(577, 44, "국물", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(578, 44, "국물", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(579, 44, "국물", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(580, 44, "국물", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(581, 45, "기본 재료", "한우 불고기용", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(582, 45, "기본 재료", "알배추", "1", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(583, 45, "기본 재료", "깻잎", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(584, 45, "기본 재료", "청경채", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(585, 45, "기본 재료", "만가닥버섯", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(586, 45, "기본 재료", "팽이버섯", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(587, 45, "기본 재료", "표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(588, 45, "육수", "물", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(589, 45, "육수", "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(590, 45, "육수", "다시마", "3", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(591, 45, "육수", "무", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(592, 45, "육수", "표고버섯밑둥", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(593, 45, "육수", "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(594, 45, "육수", "소금", "두", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(595, 45, "폰즈 소스", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(596, 45, "폰즈 소스", "식초", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(597, 45, "폰즈 소스", "올리고당", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(598, 45, "폰즈 소스", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(599, 45, "폰즈 소스", "다진양파", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(600, 46, "기본 재료", "등심돈가스", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(601, 46, "기본 재료", "한 입 크기로 자른 김치", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(602, 46, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(603, 46, "기본 재료", "양파", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(604, 46, "기본 재료", "쪽파(혹은 대파)", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(605, 46, "기본 재료", "다진마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(606, 46, "기본 재료", "튀김유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(607, 46, "양념 재료", "진간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(608, 46, "양념 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(609, 46, "양념 재료", "멸치다시물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(610, 46, "양념 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(611, 46, "양념 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(612, 46, "양념 재료", "생강즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(613, 46, "양념 재료", "김치국물", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(614, 47, "기본 재료", "쇠고기", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(615, 47, "기본 재료", "우엉", "1/4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(616, 47, "기본 재료", "표고버섯", "1과1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(617, 47, "기본 재료", "느타리버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(618, 47, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(619, 47, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(620, 47, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(621, 47, "나베 국물", "쇠고기 스톡 큐브", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(622, 47, "나베 국물", "따뜻한 물", "1과1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(623, 47, "나베 국물", "맛간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(624, 47, "나베 국물", "국간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(625, 47, "나베 국물", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(626, 47, "나베 국물", "꿀", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(627, 47, "나베 국물", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(628, 47, "나베 국물", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(629, 48, "기본 재료", "야끼소바면", "2", "봉지");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(630, 48, "기본 재료", "베이컨", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(631, 48, "기본 재료", "새우", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(632, 48, "기본 재료", "양배추", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(633, 48, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(634, 48, "기본 재료", "당근", "1/5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(635, 48, "기본 재료", "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(636, 48, "기본 재료", "쪽파", "3", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(637, 48, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(638, 48, "기본 재료", "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(639, 48, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(640, 48, "소스 재료", "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(641, 48, "소스 재료", "굴소스", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(642, 48, "소스 재료", "간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(643, 48, "고면 재료", "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(644, 49, "기본 재료", "우동면", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(645, 49, "기본 재료", "쯔유 (우동용)", "6", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(646, 49, "기본 재료", "물", "350", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(647, 49, "기본 재료", "레몬", "2", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(648, 49, "기본 재료", "김밥 김", "1/2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(649, 49, "기본 재료", "쪽파", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(650, 49, "기본 재료", "다진 생강", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(651, 49, "튀김 재료", "청고추", "5~6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(652, 49, "튀김 재료", "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(653, 49, "튀김 재료", "차가운 물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(654, 49, "튀김 재료", "식용유", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(655, 50, "기본 재료", "인스턴트 라면(사리곰탕)", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(656, 50, "기본 재료", "라면수프", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(657, 50, "기본 재료", "미소 된장", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(658, 50, "기본 재료", "버터", "2", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(659, 50, "기본 재료", "슬라이스 햄", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(660, 50, "기본 재료", "물", "1", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(661, 50, "기본 재료", "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(662, 50, "기본 재료", "캔 옥수수", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(663, 50, "기본 재료", "대파(쪽파로 대체 가능)", "1/4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(664, 50, "기본 재료", "반숙 달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(665, 51, "기본 재료", "우동면", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(666, 51, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(667, 51, "기본 재료", "청양고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(668, 51, "기본 재료", "닭다리살", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(669, 51, "기본 재료", "다시마 멸치 육수", "4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(670, 51, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(671, 51, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(672, 51, "국물 양념 재료", "쯔유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(673, 51, "국물 양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(674, 52, "기본 재료", "스파게티면", "130", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(675, 52, "기본 재료", "양배추", "3", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(676, 52, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(677, 52, "기본 재료", "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(678, 52, "기본 재료", "베이컨슬라이스", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(679, 52, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(680, 52, "기본 재료", "페페론치니", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(681, 52, "기본 재료", "가츠오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(682, 52, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(683, 52, "소스 재료", "굴소스", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(684, 52, "소스 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(685, 52, "소스 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(686, 52, "소스 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(687, 52, "소스 재료", "케첩", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(688, 52, "소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(689, 53, "기본 재료", "쇠고기", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(690, 53, "기본 재료", "우동면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(691, 53, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(692, 53, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(693, 53, "기본 재료", "카레가루", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(694, 53, "기본 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(695, 53, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(696, 53, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(697, 53, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(698, 53, "다시마물 재료", "물", "1", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(699, 53, "다시마물 재료", "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(700, 53, "다시마물 재료", "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(701, 54, "기본 재료", "메밀면", "250", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(702, 54, "기본 재료", "실파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(703, 54, "기본 재료", "김", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(704, 54, "기본 재료", "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(705, 54, "기본 재료", "새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(706, 54, "기본 재료", "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(707, 54, "기본 재료", "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(708, 54, "기본 재료", "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(709, 54, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(710, 54, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(711, 54, "기본 재료", "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(712, 54, "기본 재료", "얼음", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(713, 54, "가쓰오부시 육수", "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(714, 54, "가쓰오부시 육수", "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(715, 54, "가쓰오부시 육수", "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(716, 54, "가쓰오부시 육수", "가쓰오부시", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(717, 54, "국물 양념", "간장", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(718, 54, "국물 양념", "맛술", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(719, 54, "국물 양념", "설탕", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(720, 54, "튀김 반죽", "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(721, 54, "튀김 반죽", "차가운 물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(722, 54, "튀김 반죽", "얼음", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(723, 55, "기본 재료", "생면", "2", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(724, 55, "기본 재료", "새우", "6", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(725, 55, "기본 재료", "오징어", "1/2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(726, 55, "기본 재료", "바지락", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(727, 55, "기본 재료", "홍합", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(728, 55, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(729, 55, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(730, 55, "기본 재료", "통마늘", "2", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(731, 55, "기본 재료", "알배추", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(732, 55, "기본 재료", "청양고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(733, 55, "기본 재료", "청경채", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(734, 55, "기본 재료", "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(735, 55, "기본 재료", "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(736, 55, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(737, 55, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(738, 55, "육수", "시판용 사골 육수", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(739, 55, "육수", "물", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(740, 55, "소스", "굴소스", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(741, 55, "소스", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(742, 56, "기본 재료", "해조미 톳 국수", "1", "팩");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(743, 56, "기본 재료", "실파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(744, 56, "기본 재료", "김", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(745, 56, "기본 재료", "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(746, 56, "기본 재료", "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(747, 56, "기본 재료", "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(748, 56, "기본 재료", "얼음", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(749, 56, "육수 양념", "쯔유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(750, 56, "육수 양념", "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(751, 57, "기본 재료", "소고기 안심(스테이크용)", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(752, 57, "기본 재료", "진간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(753, 57, "기본 재료", "꿀", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(754, 57, "기본 재료", "전분가루", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(755, 57, "기본 재료", "소바 면", "170", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(756, 57, "기본 재료", "다진 쪽파", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(757, 57, "기본 재료", "볶은 통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(758, 57, "기본 재료", "올리브유", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(759, 57, "소스 재료", "진간장", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(760, 57, "소스 재료", "꿀", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(761, 57, "소스 재료", "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(762, 57, "소스 재료", "레몬 제스트", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(763, 57, "소스 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(764, 57, "소스 재료", "생강즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(765, 57, "소스 재료", "다진 마늘", "1/4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(766, 58, "기본 재료", "메밀면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(767, 58, "기본 재료", "오이", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(768, 58, "기본 재료", "깻잎", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(769, 58, "기본 재료", "삶은 달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(770, 58, "참깨 소스 재료", "볶은 참깨", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(771, 58, "참깨 소스 재료", "쯔유(모밀용)", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(772, 58, "참깨 소스 재료", "물", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(773, 58, "참깨 소스 재료", "마요네즈", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(774, 58, "참깨 소스 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(775, 58, "참깨 소스 재료", "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(776, 59, "기본 재료", "메밀면", "2", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(777, 59, "육수 A", "생수", "1.2", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(778, 59, "육수 A", "디포리", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(779, 59, "육수 A", "양파", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(780, 59, "육수 A", "건표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(781, 59, "육수 A", "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(782, 59, "육수 A", "생강즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(783, 59, "육수 B", "가쓰오부시", "2", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(784, 59, "육수 B", "진간장", "4", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(785, 59, "육수 B", "설탕", "1", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(786, 59, "육수 B", "맛술", "1", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(787, 59, "고명", "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(788, 59, "고명", "배", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(789, 59, "고명", "쪽파", "4", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(790, 59, "고명", "김가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(791, 59, "고명", "참깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(792, 60, "기본 재료", "연어 (횟감)", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(793, 60, "기본 재료", "아보카도", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(794, 60, "기본 재료", "김 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(795, 60, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(796, 60, "기본 재료", "송송 썬 쪽파 (생략 가능)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(797, 60, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(798, 60, "기본 재료", "달걀 노른자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(799, 60, "간장 소스 재료", "간장", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(800, 60, "간장 소스 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(801, 60, "간장 소스 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(802, 60, "간장 소스 재료", "고추냉이", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(803, 60, "간장 소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(804, 60, "밥 밑간 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(805, 60, "밥 밑간 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(806, 60, "밥 밑간 재료", "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(807, 61, "기본 재료", "순살 고등어", "2", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(808, 61, "기본 재료", "양배추", "1/8", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(809, 61, "기본 재료", "적양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(810, 61, "기본 재료", "실파", "2", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(811, 61, "기본 재료", "연와사비", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(812, 61, "기본 재료", "레몬(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(813, 61, "기본 재료", "잎채소", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(814, 61, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(815, 61, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(816, 61, "고등어 밑간 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(817, 61, "고등어 밑간 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(818, 61, "고등어 밑간 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(819, 61, "데리야키 소스 재료", "물", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(820, 61, "데리야키 소스 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(821, 61, "데리야키 소스 재료", "물엿", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(822, 61, "데리야키 소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(823, 61, "데리야키 소스 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(824, 61, "데리야키 소스 재료", "생강 가루", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(825, 62, "기본 재료", "생새우", "6", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(826, 62, "기본 재료", "단호박", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(827, 62, "기본 재료", "연근", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(828, 62, "기본 재료", "깻잎", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(829, 62, "기본 재료", "표고버섯", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(830, 62, "기본 재료", "꽈리고추", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(831, 62, "기본 재료", "김", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(832, 62, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(833, 62, "기본 재료", "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(834, 62, "튀김옷 재료", "튀김가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(835, 62, "튀김옷 재료", "찬물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(836, 62, "튀김옷 재료", "탄산수", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(837, 62, "튀김옷 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(838, 62, "소스 재료", "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(839, 62, "소스 재료", "물", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(840, 62, "소스 재료", "미림", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(841, 62, "소스 재료", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(842, 62, "소스 재료", "다시마(4*4cm)", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(843, 62, "소스 재료", "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(844, 63, "기본 재료", "쇠고기(불고기용)", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(845, 63, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(846, 63, "기본 재료", "느타리버섯", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(847, 63, "기본 재료", "달걀(노른자)", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(848, 63, "기본 재료", "초생강(생략가능)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(849, 63, "기본 재료", "쪽파(또는 대파)", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(850, 63, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(851, 63, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(852, 63, "양념 재료", "물", "300", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(853, 63, "양념 재료", "다시마", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(854, 63, "양념 재료", "가쓰오부시", "1", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(855, 63, "양념 재료", "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(856, 63, "양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(857, 63, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(858, 63, "양념 재료", "다진마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(859, 63, "양념 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(860, 64, "기본 재료", "장어", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(861, 64, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(862, 64, "기본 재료", "생강(마늘 1쪽 크기)", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(863, 64, "기본 재료", "실파", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(864, 64, "기본 재료", "와사비", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(865, 64, "장어 밑간 재료", "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(866, 64, "장어 밑간 재료", "소금", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(867, 64, "장어 밑간 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(868, 64, "간장소스 재료", "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(869, 64, "간장소스 재료", "맛술", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(870, 64, "간장소스 재료", "물엿", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(871, 64, "간장소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(872, 64, "간장소스 재료", "물", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(873, 64, "간장소스 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(874, 64, "간장소스 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(875, 64, "간장소스 재료", "통마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(866, 64, "간장소스 재료", "생강(마늘 1쪽 크기)", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(877, 64, "간장소스 재료", "통후추", "5", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(878, 65, "기본 재료", "밥", "1", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(879, 65, "기본 재료", "연어", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(880, 65, "기본 재료", "쪽파", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(881, 65, "기본 재료", "녹차가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(882, 65, "기본 재료", "뜨거운 물", "2 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(883, 65, "기본 재료", "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(884, 65, "기본 재료", "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(885, 65, "기본 재료", "허브솔트", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(886, 65, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(887, 66, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(888, 66, "기본 재료", "삼겹살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(889, 66, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(890, 66, "기본 재료", "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(891, 66, "기본 재료", "청주", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(892, 66, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(893, 66, "기본 재료", "대파", "10", "cm");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(894, 66, "기본 재료", "마늘", "5", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(895, 66, "기본 재료", "생강가루", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(896, 66, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(897, 66, "소스", "물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(898, 66, "소스", "가쓰오부시 장국", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(899, 66, "소스", "맛술", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(900, 66, "소스", "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(901, 66, "소스", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(902, 66, "곁들임 야채", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(903, 66, "곁들임 야채", "깻잎", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(904, 66, "곁들임 야채", "쪽파", "4", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(905, 67, "기본 재료", "생연어", "600", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(906, 67, "기본 재료", "양파", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(907, 67, "기본 재료", "홍고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(908, 67, "기본 재료", "청양고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(909, 67, "기본 재료", "레몬", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(910, 67, "기본 재료", "가츠오부시", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(911, 67, "간장물 재료", "간장", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(912, 67, "간장물 재료", "맛술", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(913, 67, "간장물 재료", "물", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(914, 67, "간장물 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(915, 67, "간장물 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(916, 67, "간장물 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(917, 67, "간장물 재료", "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(918, 67, "간장물 재료", "생강(마늘 2쪽 사이즈)", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(919, 67, "간장물 재료", "마른고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(920, 67, "간장물 재료", "통후추", "10", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(921, 68, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(922, 68, "기본 재료", "묵은지", "1/4", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(923, 68, "기본 재료", "명이나물 장아찌", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(924, 68, "기본 재료", "차돌박이", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(925, 68, "기본 재료", "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(926, 68, "기본 재료", "실파", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(927, 68, "기본 재료", "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(928, 68, "기본 재료", "깨소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(929, 68, "배합초", "식초", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(930, 68, "배합초", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(931, 68, "배합초", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(932, 68, "차돌박이 양념", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(933, 68, "차돌박이 양념", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(934, 68, "차돌박이 양념", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(935, 68, "차돌박이 양념", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(936, 68, "차돌박이 양념", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(937, 69, "기본 재료", "전복", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(938, 69, "기본 재료", "시소", "6", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(939, 69, "기본 재료", "달걀물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(940, 69, "기본 재료", "박력분", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(941, 69, "기본 재료", "식용유", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(942, 69, "튀김 소스", "가쓰오 다시", "4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(943, 69, "튀김 소스", "미림", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(944, 69, "튀김 소스", "진간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(945, 69, "튀김 소스", "무 간 것", "40", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(946, 69, "달걀물", "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(947, 69, "달걀물", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(948, 69, "달걀물", "탄산수", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(949, 70, "기본 재료", "고등어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(950, 70, "기본 재료", "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(951, 70, "기본 재료", "꽈리고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(952, 70, "기본 재료", "생강", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(953, 70, "소스", "백된장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(954, 70, "소스", "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(955, 70, "소스", "정종", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(956, 70, "소스", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(957, 70, "소스", "연간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(958, 71, "기본 재료", "달걀", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(959, 71, "기본 재료", "생 연어(연어 통조림 또는 훈제연어)", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(960, 71, "기본 재료", "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(961, 71, "기본 재료", "가쓰오부시", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(962, 71, "기본 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(963, 71, "기본 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(964, 71, "기본 재료", "소금", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(965, 71, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(966, 71, "소스 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(967, 71, "소스 재료", "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(968, 71, "소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(969, 71, "소스 재료", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(970, 71, "소스 재료", "생강(슬라이스)", "1", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(971, 72, "기본 재료", "문어", "120", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(972, 72, "기본 재료", "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(973, 72, "기본 재료", "쪽파", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(974, 72, "기본 재료", "파래가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(975, 72, "기본 재료", "마요네즈", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(976, 72, "기본 재료", "돈가스 소스(또는 우스터 소스)", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(977, 72, "기본 재료", "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(978, 72, "반죽 재료", "밀가루", "110", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(979, 72, "반죽 재료", "찹쌀가루", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(980, 72, "반죽 재료", "베이킹 파우더", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(981, 72, "반죽 재료", "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(982, 72, "반죽 재료", "다시마육수", "360", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(983, 73, "기본 재료", "돼지고기(등심 또는 안심)", "400", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(984, 73, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(985, 73, "기본 재료", "밀가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(986, 73, "기본 재료", "빵가루", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(987, 73, "기본 재료", "모차렐라치즈블럭(또는 피자치즈)"), "200", "g";
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(988, 73, "기본 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(989, 73, "기본 재료", "시판 돈가스소스", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(990, 73, "기본 재료", "깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(991, 73, "기본 재료", "연겨자(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(992, 73, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(993, 73, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(994, 74, "기본 재료", "두부(찌개용)", "1", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(995, 74, "기본 재료", "전분가루", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(996, 74, "기본 재료", "실파", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(997, 74, "기본 재료", "무", "1/8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(998, 74, "기본 재료", "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(999, 74, "소스 재료", "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1000, 74, "소스 재료", "다시마(사방 4센치)", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1001, 74, "소스 재료", "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1002, 74, "소스 재료", "미림", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1003, 75, "기본 재료", "닭다리살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1004, 75, "기본 재료", "양배추", "3", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1005, 75, "기본 재료", "레몬(생략가능)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1006, 75, "기본 재료", "전분가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1007, 75, "기본 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1008, 75, "기본 재료", "튀김기름", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1009, 75, "밑간 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1010, 75, "밑간 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1011, 75, "밑간 재료", "생강가루", "1/4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1012, 75, "밑간 재료", "소금", "두", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1013, 75, "밑간 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1014, 76, "기본 재료", "식빵", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1015, 76, "기본 재료", "새우", "4", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1016, 76, "기본 재료", "양배추", "2", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1017, 76, "기본 재료", "로켓잎(또는 치커리)", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1018, 76, "기본 재료", "밀가루", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1019, 76, "기본 재료", "빵가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1020, 76, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1021, 76, "기본 재료", "마요네즈", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1022, 76, "기본 재료", "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1023, 76, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1024, 76, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1025, 77, "기본 재료", "냉동참치", "1", "토막");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1026, 77, "기본 재료", "어린잎채소", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1027, 77, "기본 재료", "라임 또는 레몬", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1028, 77, "기본 재료", "래디사", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1029, 77, "기본 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1030, 77, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1031, 77, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1032, 77, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1033, 77, "드레싱", "올리브오일", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1034, 77, "드레싱", "다진 사과", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1035, 77, "드레싱", "홀그레인머스터드", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1036, 77, "드레싱", "식초", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1037, 77, "드레싱", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1038, 77, "드레싱", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1039, 77, "드레싱", "라임즙 또는 레몬즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1040, 78, "기본 재료", "양배추", "1/8", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1041, 78, "기본 재료", "달래", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1042, 78, "기본 재료", "오징어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1043, 78, "기본 재료", "베이컨", "3", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1044, 78, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1045, 78, "반죽 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1046, 78, "반죽 재료", "부침가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1047, 78, "반죽 재료", "물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1048, 78, "반죽 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1049, 78, "반죽 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1050, 78, "소스", "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1051, 78, "소스", "마요네즈", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1052, 78, "소스", "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1053, 79, "기본 재료", "새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1054, 79, "기본 재료", "시사모(열빙어)", "4", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1055, 79, "기본 재료", "닭다리살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1056, 79, "기본 재료", "대파", "2~3", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1057, 79, "기본 재료", "마늘", "10", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1058, 79, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1059, 79, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1060, 79, "기본 재료", "청주", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1061, 79, "소스", "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1062, 79, "소스", "미림", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1063, 79, "소스", "청주", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1064, 79, "소스", "설탕", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1065, 79, "소스", "꿀", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1066, 79, "소스", "다진 생강", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1067, 80, "기본 재료", "물오징어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1068, 80, "기본 재료", "빵가루", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1069, 80, "기본 재료", "박력분", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1070, 80, "기본 재료", "식용유", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1071, 80, "소스", "단무지", "20", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1072, 80, "소스", "오이", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1073, 80, "소스", "와사비", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1074, 80, "소스", "마요네즈", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1075, 80, "달걀물", "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1076, 80, "달걀물", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1077, 80, "달걀물", "탄산수", "1", "큰술");