insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(531, 41, "쇠고기등심", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(532, 41, "두부", "1/3", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(533, 41, "실곤약", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(534, 41, "실곤약", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(535, 41, "표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(536, 41, "배추", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(537, 41, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(538, 41, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(539, 41, "쑥갓", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(540, 41, "다시마육수", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(541, 41, "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(542, 41, "우동면", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(543, 41, "맛술", "2/3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(544, 41, "간장", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(545, 41, "청주", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(546, 41, "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(547, 42, "다시마", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(548, 42, "가쓰오부시", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(549, 42, "가쓰오 다시", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(550, 42, "정종", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(550, 42, "미림", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(551, 42, "건미역", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(552, 42, "연두부", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(553, 42, "팽이버섯", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(554, 42, "된장", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(555, 42, "일본 미소시루용 된장", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(556, 42, "정종", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(557, 42, "미림", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(558, 43, "옥도미", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(559, 43, "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(560, 43, "구운 대파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(561, 43, "유자 껍질", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(562, 43, "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(563, 43, "정종", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(564, 43, "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(565, 43, "소금", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(566, 44, "모듬어묵", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(567, 44, "곤약", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(568, 44, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(569, 44, "마늘", "1", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(570, 44, "무", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(571, 44, "건고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(572, 44, "연겨자", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(573, 44, "삶은 달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(574, 44, "물", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(575, 44, "멸치", "10", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(576, 44, "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(577, 44, "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(578, 44, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(579, 44, "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(580, 44, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(581, 45, "한우 불고기용", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(582, 45, "알배추", "1", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(583, 45, "깻잎", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(584, 45, "청경채", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(585, 45, "만가닥버섯", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(586, 45, "팽이버섯", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(587, 45, "표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(588, 45, "물", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(589, 45, "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(590, 45, "다시마", "3", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(591, 45, "무", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(592, 45, "표고버섯밑둥", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(593, 45, "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(594, 45, "소금", "두", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(595, 45, "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(596, 45, "식초", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(597, 45, "올리고당", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(598, 45, "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(599, 45, "다진양파", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(600, 46, "등심돈가스", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(601, 46, "한 입 크기로 자른 김치", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(602, 46, "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(603, 46, "양파", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(604, 46, "쪽파(혹은 대파)", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(605, 46, "다진마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(606, 46, "튀김유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(607, 46, "진간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(608, 46, "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(609, 46, "멸치다시물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(610, 46, "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(611, 46, "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(612, 46, "생강즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(613, 46, "김치국물", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(614, 47, "쇠고기", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(615, 47, "우엉", "1/4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(616, 47, "표고버섯", "1과1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(617, 47, "느타리버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(618, 47, "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(619, 47, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(620, 47, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(621, 47, "쇠고기 스톡 큐브", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(622, 47, "따뜻한 물", "1과1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(623, 47, "맛간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(624, 47, "국간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(625, 47, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(626, 47, "꿀", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(627, 47, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(628, 47, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(629, 48, "야끼소바면", "2", "봉지");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(630, 48, "베이컨", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(631, 48, "새우", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(632, 48, "양배추", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(633, 48, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(634, 48, "당근", "1/5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(635, 48, "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(636, 48, "쪽파", "3", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(637, 48, "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(638, 48, "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(639, 48, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(640, 48, "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(641, 48, "굴소스", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(642, 48, "간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(643, 48, "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(644, 49, "우동면", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(645, 49, "쯔유 (우동용)", "6", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(646, 49, "물", "350", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(647, 49, "레몬", "2", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(648, 49, "김밥 김", "1/2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(649, 49, "쪽파", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(650, 49, "다진 생강", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(651, 49, "청고추", "5~6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(652, 49, "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(653, 49, "차가운 물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(654, 49, "식용유", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(655, 50, "인스턴트 라면(사리곰탕)", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(656, 50, "라면수프", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(657, 50, "미소 된장", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(658, 50, "버터", "2", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(659, 50, "슬라이스 햄", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(660, 50, "물", "1", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(661, 50, "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(662, 50, "캔 옥수수", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(663, 50, "대파(쪽파로 대체 가능)", "1/4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(664, 50, "반숙 달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(665, 51, "우동면", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(666, 51, "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(667, 51, "청양고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(668, 51, "닭다리살", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(669, 51, "다시마 멸치 육수", "4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(670, 51, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(671, 51, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(672, 51, "쯔유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(673, 51, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(674, 52, "스파게티면", "130", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(675, 52, "양배추", "3", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(676, 52, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(677, 52, "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(678, 52, "베이컨슬라이스", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(679, 52, "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(680, 52, "페페론치니", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(681, 52, "가츠오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(682, 52, "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(683, 52, "굴소스", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(684, 52, "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(685, 52, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(686, 52, "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(687, 52, "케첩", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(688, 52, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(689, 53, "쇠고기", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(690, 53, "우동면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(691, 53, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(692, 53, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(693, 53, "카레가루", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(694, 53, "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(695, 53, "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(696, 53, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(697, 53, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(698, 53, "물", "1", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(699, 53, "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(700, 53, "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(701, 54, "메밀면", "250", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(702, 54, "실파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(703, 54, "김", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(704, 54, "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(705, 54, "새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(706, 54, "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(707, 54, "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(708, 54, "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(709, 54, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(710, 54, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(711, 54, "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(712, 54, "얼음", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(713, 54, "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(714, 54, "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(715, 54, "멸치", "10", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(716, 54, "가쓰오부시", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(717, 54, "간장", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(718, 54, "맛술", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(719, 54, "설탕", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(720, 54, "튀김가루", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(721, 54, "차가운 물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(722, 54, "얼음", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(723, 55, "생면", "2", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(724, 55, "새우", "6", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(725, 55, "오징어", "1/2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(726, 55, "바지락", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(727, 55, "홍합", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(728, 55, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(729, 55, "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(730, 55, "통마늘", "2", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(731, 55, "알배추", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(732, 55, "청양고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(733, 55, "청경채", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(734, 55, "숙주", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(735, 55, "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(736, 55, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(737, 55, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(738, 55, "시판용 사골 육수", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(739, 55, "물", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(740, 55, "굴소스", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(741, 55, "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(742, 56, "해조미 톳 국수", "1", "팩");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(743, 56, "실파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(744, 56, "김", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(745, 56, "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(746, 56, "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(747, 56, "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(748, 56, "얼음", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(749, 56, "쯔유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(750, 56, "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(751, 57, "소고기 안심(스테이크용)", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(752, 57, "진간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(753, 57, "꿀", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(754, 57, "전분가루", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(755, 57, "소바 면", "170", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(756, 57, "다진 쪽파", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(757, 57, "볶은 통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(758, 57, "올리브유", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(759, 57, "진간장", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(760, 57, "꿀", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(761, 57, "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(762, 57, "레몬 제스트", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(763, 57, "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(764, 57, "생강즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(765, 57, "다진 마늘", "1/4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(766, 58, "메밀면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(767, 58, "오이", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(768, 58, "깻잎", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(769, 58, "삶은 달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(770, 58, "볶은 참깨", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(771, 58, "쯔유(모밀용)", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(772, 58, "물", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(773, 58, "마요네즈", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(774, 58, "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(775, 58, "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(776, 59, "메밀면", "2", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(777, 59, "생수", "1.2", "L");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(778, 59, "디포리", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(779, 59, "양파", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(780, 59, "건표고버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(781, 59, "다시마", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(782, 59, "생강즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(783, 59, "가쓰오부시", "2", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(784, 59, "진간장", "4", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(785, 59, "설탕", "1", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(786, 59, "맛술", "1", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(787, 59, "무", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(788, 59, "배", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(789, 59, "쪽파", "4", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(790, 59, "김가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(791, 59, "참깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(792, 60, "연어 (횟감)", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(793, 60, "아보카도", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(794, 60, "김 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(795, 60, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(796, 60, "송송 썬 쪽파 (생략 가능)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(797, 60, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(798, 60, "달걀 노른자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(799, 60, "간장", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(800, 60, "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(801, 60, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(802, 60, "고추냉이", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(803, 60, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(804, 60, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(805, 60, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(806, 60, "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(807, 61, "순살 고등어", "2", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(808, 61, "양배추", "1/8", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(809, 61, "적양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(810, 61, "실파", "2", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(811, 61, "연와사비", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(812, 61, "레몬(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(813, 61, "잎채소", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(814, 61, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(815, 61, "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(816, 61, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(817, 61, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(818, 61, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(819, 61, "물", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(820, 61, "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(821, 61, "물엿", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(822, 61, "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(823, 61, "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(824, 61, "생강 가루", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(825, 62, "생새우", "6", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(826, 62, "단호박", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(827, 62, "연근", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(828, 62, "깻잎", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(829, 62, "표고버섯", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(830, 62, "꽈리고추", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(831, 62, "김", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(832, 62, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(833, 62, "튀김가루", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(834, 62, "찬물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(835, 62, "탄산수", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(836, 62, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(837, 62, "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(838, 62, "물", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(839, 62, "미림", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(840, 62, "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(841, 62, "다시마(4*4cm)", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(842, 62, "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(843, 63, "쇠고기(불고기용)", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(844, 63, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(845, 63, "느타리버섯", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(846, 63, "달걀(노른자)", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(847, 63, "초생강(생략가능)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(848, 63, "쪽파(또는 대파)", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(849, 63, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(850, 63, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(851, 63, "물", "300", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(852, 63, "다시마", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(853, 63, "가쓰오부시", "1", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(854, 63, "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(855, 63, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(856, 63, "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(857, 63, "다진마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(858, 63, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(859, 64, "장어", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(860, 64, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(861, 64, "생강(마늘 1쪽 크기)", "2", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(862, 64, "실파", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(863, 64, "와사비", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(864, 64, "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(865, 64, "소금", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(866, 64, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(867, 64, "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(868, 64, "맛술", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(869, 64, "물엿", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(870, 64, "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(871, 64, "물", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(872, 64, "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(873, 64, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(874, 64, "통마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(875, 64, "통후추", "5", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(876, 65, "밥", "1", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(877, 65, "연어", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(878, 65, "쪽파", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(879, 65, "녹차가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(880, 65, "뜨거운 물", "2 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(881, 65, "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(882, 65, "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(883, 65, "허브솔트", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(884, 65, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(885, 66, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(886, 66, "삼겹살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(887, 66, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(888, 66, "물", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(889, 66, "청주", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(890, 66, "양파", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(891, 66, "대파", "10", "cm");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(892, 66, "마늘", "5", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(893, 66, "생강가루", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(894, 66, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(895, 66, "가쓰오부시 장국", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(896, 66, "맛술", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(897, 66, "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(898, 66, "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(899, 66, "깻잎", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(900, 66, "쪽파", "4", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(901, 67, "생연어", "600", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(902, 67, "양파", "1 + 1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(903, 67, "홍고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(904, 67, "청양고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(905, 67, "레몬", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(906, 67, "가츠오부시", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(907, 67, "간장", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(908, 67, "맛술", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(909, 67, "물", "1 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(910, 67, "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(911, 67, "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(912, 67, "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(913, 67, "생강(마늘 2쪽 사이즈)", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(914, 67, "마른고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(915, 67, "통후추", "10", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(916, 68, "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(917, 68, "묵은지", "1/4", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(918, 68, "명이나물 장아찌", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(919, 68, "차돌박이", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(920, 68, "무순", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(921, 68, "실파", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(922, 68, "고추냉이", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(923, 68, "깨소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(924, 68, "식초", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(925, 68, "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(926, 68, "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(927, 68, "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(928, 68, "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(929, 68, "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(930, 68, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(931, 69, "전복", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(932, 69, "시소", "6", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(933, 69, "달걀물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(934, 69, "박력분", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(935, 69, "식용유", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(936, 69, "가쓰오 다시", "4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(937, 69, "미림", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(938, 69, "진간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(939, 69, "무 간 것", "40", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(940, 69, "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(941, 69, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(942, 69, "탄산수", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(943, 70, "고등어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(944, 70, "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(945, 70, "꽈리고추", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(946, 70, "생강", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(947, 70, "백된장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(948, 70, "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(949, 70, "정종", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(950, 70, "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(951, 70, "연간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(952, 71, "달걀", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(953, 71, "생 연어(연어 통조림 또는 훈제연어)", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(954, 71, "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(955, 71, "가쓰오부시", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(956, 71, "맛술", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(957, 71, "설탕", "4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(958, 71, "소금", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(959, 71, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(960, 71, "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(961, 71, "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(962, 71, "생강(슬라이스)", "1", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(963, 71, "문어", "120", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(964, 71, "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(965, 72, "쪽파", "반", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(966, 72, "파래가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(967, 72, "마요네즈", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(968, 72, "돈가스 소스(또는 우스터 소스)", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(969, 72, "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(970, 72, "밀가루", "110", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(971, 72, "찹쌀가루", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(972, 72, "베이킹 파우더", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(973, 72, "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(974, 72, "다시마육수", "360", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(975, 73, "돼지고기(등심 또는 안심)", "400", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(976, 73, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(977, 73, "밀가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(978, 73, "빵가루", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(979, 73, "모차렐라치즈블럭(또는 피자치즈)"), "200", "g";
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(980, 73, "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(981, 73, "시판 돈가스소스", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(982, 73, "깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(983, 73, "연겨자(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(984, 73, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(985, 73, "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(986, 74, "두부(찌개용)", "1", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(987, 74, "전분가루", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(988, 74, "실파", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(989, 74, "무", "1/8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(990, 74, "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(991, 74, "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(992, 74, "다시마(사방 4센치)", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(993, 74, "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(994, 74, "미림", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(995, 75, "닭다리살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(996, 75, "양배추", "3", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(997, 75, "레몬(생략가능)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(998, 75, "전분가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(999, 75, "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1000, 75, "튀김기름", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1001, 75, "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1002, 75, "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1003, 75, "생강가루", "1/4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1004, 75, "소금", "두", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1005, 75, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1006, 76, "식빵", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1007, 76, "새우", "4", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1008, 76, "양배추", "2", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1009, 76, "로켓잎(또는 치커리)", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1010, 76, "밀가루", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1011, 76, "빵가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1012, 76, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1013, 76, "마요네즈", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1014, 76, "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1015, 76, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1016, 76, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1017, 77, "냉동참치", "1", "토막");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1018, 77, "어린잎채소", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1019, 77, "라임 또는 레몬", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1020, 77, "래디사", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1021, 77, "올리브오일", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1022, 77, "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1023, 77, "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1024, 77, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1025, 77, "다진 사과", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1026, 77, "홀그레인머스터드", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1027, 77, "식초", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1028, 77, "라임즙 또는 레몬즙", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1029, 78, "양배추", "1/8", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1030, 78, "달래", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1031, 78, "오징어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1032, 78, "베이컨", "3", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1033, 78, "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1034, 78, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1035, 78, "부침가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1036, 78, "물", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1037, 78, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1038, 78, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1039, 78, "돈가스 소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1040, 78, "마요네즈", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1041, 78, "가쓰오부시", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1042, 79, "새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1043, 79, "시사모(열빙어)", "4", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1044, 79, "닭다리살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1045, 79, "대파", "2~3", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1046, 79, "마늘", "10", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1047, 79, "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1048, 79, "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1049, 79, "청주", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1050, 79, "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1051, 79, "미림", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1052, 79, "설탕", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1053, 79, "꿀", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1054, 79, "다진 생강", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1055, 80, "물오징어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1056, 80, "빵가루", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1057, 80, "박력분", null, "조금");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1058, 80, "식용유", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1059, 80, "단무지", "20", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1060, 80, "오이", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1061, 80, "와사비", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1062, 80, "마요네즈", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1063, 80, "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1064, 80, "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1065, 80, "탄산수", "1", "큰술");