insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(1, 1, "기본 재료", "성게", "60", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(2, 1, "기본 재료", "건 미역", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(3, 1, "기본 재료", "다시마 육수", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(4, 1, "기본 재료", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(5, 1, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(6, 1, "기본 재료", "멸치액젓", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(7, 1, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(8, 2, "기본 재료", "생 곤드레", 200, "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(9, 2, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(10, 2, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(11, 2, "반죽 재료", "부침가루", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(12, 2, "반죽 재료", "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(13, 2, "양념장 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(14, 2, "양념장 재료", "맛술", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(15, 2, "양념장 재료", "식초", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(16, 2, "양념장 재료", "잘게 썬 양파", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(17, 2, "양념장 재료", "잘게 썬 홍고추", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(18, 2, "양념장 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(19, 3, "기본 재료", "불린 미역", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(20, 3, "기본 재료", "생수", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(21, 3, "기본 재료", "오이", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(22, 3, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(23, 3, "기본 재료", "얼음", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(24, 3, "양념 재료", "식초", "1/3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(25, 3, "양념 재료", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(26, 3, "양념 재료", "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(27, 3, "양념 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(28, 3, "양념 재료", "다진 마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(29, 4, "기본 재료", "아욱", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(30, 4, "기본 재료", "멸치 다시마 육수", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(31, 4, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(32, 4, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(33, 4, "기본 재료", "된장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(34, 4, "기본 재료", "고추장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(35, 4, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(36, 5, "기본 재료", "목살", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(37, 5, "기본 재료", "신김치", "1/2", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(38, 5, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(39, 5, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(40, 5, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(41, 5, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(42, 5, "기본 재료", "멸치다시마육수(또는 쌀뜨물)", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(43, 5, "기본 재료", "된장(생략 가능)", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(44, 5, "양념 재료", "김치국물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(45, 5, "양념 재료", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(46, 5, "양념 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(47, 5, "양념 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(48, 5, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(49, 5, "양념 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(50, 5, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(51, 6, "기본 재료", "신김치", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(52, 6, "기본 재료", "중면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(53, 6, "기본 재료", "오이", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(54, 6, "기본 재료", "깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(55, 6, "양념 재료", "고추장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(56, 6, "양념 재료", "식초", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(57, 6, "양념 재료", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(58, 6, "양념 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(59, 6, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(60, 6, "양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(61, 6, "양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(62, 6, "양념 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(63, 7, "기본 재료", "꼬막", "1", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(64, 7, "기본 재료", "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(65, 7, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(66, 7, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(67, 7, "기본 재료", "청양고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(68, 7, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(69, 7, "기본 재료", "통깨", null, "약갼");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(70, 7, "양념 재료", "간장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(71, 7, "양념 재료", "고춧가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(72, 7, "양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(73, 7, "양념 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(74, 7, "양념 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(75, 7, "양념 재료", "생강즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(76, 7, "양념 재료", "다진마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(77, 7, "양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(78, 7, "양념 재료", "깨소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(79, 7, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(80, 8, "기본 재료", "소고기(설도)", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(81, 8, "기본 재료", "양파", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(82, 8, "기본 재료", "당근", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(83, 8, "기본 재료", "대파", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(84, 8, "기본 재료", "배", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(85, 8, "기본 재료", "진간장", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(86, 8, "기본 재료", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(87, 8, "기본 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(88, 8, "기본 재료", "후추", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(89, 8, "기본 재료", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(90, 8, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(91, 8, "기본 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(92, 9, "기본 재료", "감자", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(93, 9, "기본 재료", "당근", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(94, 9, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(95, 9, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(96, 9, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(97, 9, "양념 재료", "다진 마늘", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(98, 9, "양념 재료", "소금", "1/4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(99, 10, "기본 재료", "자른 쇠고기 양지(또는 등심)", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(100, 10, "기본 재료", "자른 미역", "20", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(101, 10, "기본 재료", "참기름(또는 들기름)", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(102, 10, "기본 재료", "국간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(103, 10, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(104, 10, "양념 재료", "물(또는 쌀뜨물)", "7", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(105, 10, "양념 재료", "멸치 액젓(또는 참치액젓)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(106, 11, "기본 재료", "돼지고기(앞다릿살 또는 목살)", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(107, 11, "기본 재료", "배추김치(신김치)", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(108, 11, "기본 재료", "순두부", "1", "봉");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(109, 11, "기본 재료", "대파", "1/3", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(110, 11, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(111, 11, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(112, 11, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(113, 11, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(114, 11, "기본 재료", "멸치 다시마 육수", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(115, 11, "기본 재료", "고추기름", "1과1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(116, 11, "고기 밑간 재료", "맛술", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(117, 11, "고기 밑간 재료", "참기름", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(118, 11, "고기 밑간 재료", "다진 마늘", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(119, 11, "고기 밑간 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(120, 11, "양념 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(121, 11, "양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(122, 11, "양념 재료", "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(123, 11, "양념 재료", "다진 마늘",  "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(124, 11, "양념 재료", "새우젓", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(125, 11, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(126, 12, "기본 재료", "떡국용 떡", "400", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(127, 12, "기본 재료", "다진 쇠고기", "130", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(128, 12, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(129, 12, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(130, 12, "쇠고기 양념", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(131, 12, "쇠고기 양념", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(132, 12, "쇠고기 양념", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(133, 12, "쇠고기 양념", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(134, 12, "쇠고기 양념", "후추가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(135, 12, "국물", "다시마물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(136, 12, "국물", "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(137, 12, "국물", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(138, 12, "국물", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(139, 12, "국물", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(140, 13, "기본 재료", "황태채", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(141, 13, "기본 재료", "무", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(142, 13, "기본 재료", "콩나물", "두", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(143, 13, "기본 재료", "청양고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(144, 13, "기본 재료", "홍고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(145, 13, "기본 재료", "실파", "4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(146, 13, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(147, 13, "기본 재료", "들기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(148, 13, "기본 재료", "다시마멸치육수", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(149, 13, "국물 양념", "국간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(150, 13, "국물 양념", "다진 마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(151, 13, "국물 양념", "새우젓", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(152, 13, "국물 양념", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(153, 13, "국물 양념", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(154, 14, "기본 재료", "오징어(작은 사이즈)", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(155, 14, "기본 재료", "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(156, 14, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(157, 14, "기본 재료", "청양고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(158, 14, "기본 재료", "홍고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(159, 14, "기본 재료", "다시마멸치육수", "4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(160, 14, "양념 재료", "국간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(161, 14, "양념 재료", "다진마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(162, 14, "양념 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(163, 15, "기본 재료", "콩나물", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(164, 15, "기본 재료", "쪽파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(165, 15, "기본 재료", "청양고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(166, 15, "기본 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(167, 15, "기본 재료", "새우젓", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(168, 15, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(169, 15, "기본 재료", "멸치 다시마 육수", "6", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(170, 16, "기본 재료", "묵은지", "1/4", "포기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(171, 16, "기본 재료", "참치캔(작은캔)", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(172, 16, "기본 재료", "두부", "1/2", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(173, 16, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(174, 16, "기본 재료", "대파", "1/4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(175, 16, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(176, 16, "기본 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(177, 16, "기본 재료", "들기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(178, 16, "기본 재료", "김치국물", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(179, 16, "기본 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(180, 16, "기본 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(181, 16, "기본 재료", "쌀뜨물(또는 멸치육수)",  "200", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(182, 17, "기본 재료", "표고버섯", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(183, 17, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(184, 17, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(185, 17, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(186, 17, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(187, 17, "기본 재료", "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(188, 17, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(189, 17, "기본 재료", "레드페퍼(또는 청양고추)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(190, 17, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(191, 17, "양념 재료", "간장", "1과1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(192, 17, "양념 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(193, 17, "양념 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(194, 17, "양념 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(195, 17, "양념 재료", "참기름", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(196, 17, "양념 재료", "후추가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(197, 18, "기본 재료", "스팸", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(198, 18, "기본 재료", "양파", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(199, 18, "기본 재료", "밥", "1", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(200, 18, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(201, 18, "기본 재료", "마요네즈", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(202, 18, "기본 재료", "송송 썬 쪽파", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(203, 18, "기본 재료", "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(204, 18, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(205, 18, "소스 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(206, 18, "소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(207, 18, "소스 재료", "물", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(208, 18, "소스 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(209, 19, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(210, 19, "기본 재료", "달걀", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(211, 19, "기본 재료", "물", "1/3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(212, 19, "기본 재료", "참치캔(작은캔)", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(213, 19, "기본 재료", "피자치즈", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(214, 19, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(215, 19, "기본 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(216, 19, "기본 재료", "청고추(생략 가능)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(217, 19, "기본 재료", "홍고추(생략 가능)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(218, 19, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(219, 20, "기본 재료", "콩나물", "1", "봉지");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(220, 20, "기본 재료", "삶은 달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(221, 20, "기본 재료", "쫄면", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(222, 20, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(223, 20, "양념 재료", "고추장", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(224, 20, "양념 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(225, 20, "양념 재료", "식초", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(226, 20, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(227, 20, "양념 재료", "올리고당", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(228, 20, "양념 재료", "간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(229, 20, "양념 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(230, 20, "양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(231, 20, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(232, 21, "기본 재료", "칼국수면", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(233, 21, "기본 재료", "애호박", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(234, 21, "기본 재료", "감자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(235, 21, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(236, 21, "기본 재료", "대파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(237, 21, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(238, 21, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(239, 21, "기본 재료", "구운 소금", "1/4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(240, 21, "기본 재료", "김가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(241, 21, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(242, 21, "기본 재료", "멸치 새우 다시마 육수", "7", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(243, 21, "국물 양념 재료", "고추장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(244, 21, "국물 양념 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(245, 21, "국물 양념 재료", "된장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(246, 21, "국물 양념 재료", "국간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(247, 21, "국물 양념 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(248, 21, "국물 양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(249, 22, "기본 재료", "밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(250, 22, "기본 재료", "단무지", "3", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(251, 22, "기본 재료", "당근", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(252, 22, "기본 재료", "오이" "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(253, 22, "기본 재료", "깻잎", "6", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(254, 22, "기본 재료", "청상추", "6", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(255, 22, "기본 재료", "맛살", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(256, 22, "기본 재료", "판어묵", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(257, 22, "기본 재료", "달걀", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(258, 22, "기본 재료", "김밥용 김", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(259, 22, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(260, 22, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(261, 22, "기본 재료", "맛술", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(262, 22, "밥 양념 재료", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(263, 22, "밥 양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(264, 22, "밥 양념 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(265, 22, "어묵 조림 재료", "간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(266, 22, "어묵 조림 재료", "맛술", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(267, 22, "어묵 조림 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(268, 22, "어묵 조림 재료", "올리고당", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(269, 22, "어묵 조림 재료", "물", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(270, 23, "기본 재료", "깍두기", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(271, 23, "기본 재료", "대패삼겹살", "180", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(272, 23, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(273, 23, "기본 재료", "공기밥", "2", "공기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(274, 23, "기본 재료", "김가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(275, 23, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(276, 23, "기본 재료", "쪽파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(277, 23, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(278, 23, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(279, 23, "양념 재료", "진간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(280, 23, "양념 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(281, 23, "양념 재료", "올리고당", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(282, 23, "양념 재료", "고춧가루", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(283, 23, "양념 재료", "고추장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(284, 23, "양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(285, 23, "양념 재료", "깍두기 국물", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(286, 24, "기본 재료", "소면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(287, 24, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(288, 24, "기본 재료", "쪽파", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(289, 24, "기본 재료", "김가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(290, 24, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(291, 24, "양념 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(292, 24, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(293, 24, "양념 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(294, 24, "양념 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(295, 24, "양념 재료", "다진 마늘", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(296, 24, "양념 재료", "깨소금", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(297, 25, "기본 재료", "소면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(298, 25, "기본 재료", "김치", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(299, 25, "기본 재료", "오이", "1/4","개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(300, 25, "기본 재료", "삶은달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(301, 25, "기본 재료", "청고추", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(302, 25, "기본 재료", "홍고추", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(303, 25, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(304, 25, "김치 양념 재료", "올리고당", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(305, 25, "김치 양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(306, 25, "김치 양념 재료", "참기름", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(307, 25, "국물 양념 재료료", "냉면육수", "900", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(308, 25, "국물 양념 재료료", "김치국물", "6", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(309, 25, "국물 양념 재료료", "식초", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(310, 25, "국물 양념 재료료", "설탕", "1과1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(311, 25, "국물 양념 재료료", "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(312, 26, "기본 재료", "오징어채", "3", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(313, 26, "기본 재료", "식용유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(314, 26, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(315, 26, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(316, 26, "양념 재료", "고추장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(317, 26, "양념 재료", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(318, 26, "양념 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(319, 26, "양념 재료", "마요네즈", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(320, 26, "양념 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(321, 26, "양념 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(322, 26, "양념 재료", "고운 고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(323, 26, "양념 재료", "다진 마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(324, 26, "양념 재료", "물", "1/4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(325, 26, "양념 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(326, 27, "기본 재료", "참치캔", "1", "캔");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(327, 27, "기본 재료", "썬 김치", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(328, 27, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(329, 27, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(330, 27, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(331, 27, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(332, 27, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(333, 27, "양념 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(334, 27, "양념 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(335, 27, "양념 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(336, 27, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(337, 28, "기본 재료", "청포묵", "1", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(338, 28, "기본 재료", "쪽파", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(339, 28, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(340, 28, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(341, 28, "기본 재료", "조미김", "1", "봉지");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(342, 28, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(343, 28, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(344, 28, "기본 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(345, 29, "기본 재료", "두부", "1", "모");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(346, 29, "기본 재료", "무", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(347, 29, "기본 재료", "청양고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(348, 29, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(349, 29, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(350, 29, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(351, 29, "기본 재료", "멸치 다시마 육수", "4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(352, 29, "양념 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(353, 29, "양념 재료", "고춧가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(354, 29, "양념 재료", "고추장" "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(355, 29, "양념 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(356, 29, "양념 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(357, 29, "양념 재료", "설탕", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(358, 29, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(359, 29, "양념 재료", "식용유", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(360, 29, "양념 재료", "생강가루", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(361, 29, "양념 재료", "참치액젓", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(362, 30, "기본 재료", "통조림햄", "1/2", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(363, 30, "기본 재료", "소시지", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(364, 30, "기본 재료", "양배추", "1/8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(365, 30, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(366, 30, "기본 재료", "베이크드빈스(생략 가능)", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(367, 30, "기본 재료", "대파", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(368, 30, "기본 재료", "식용유", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(369, 30, "기본 재료", "슬라이스 치즈", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(370, 30, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(371, 30, "소스 재료", "물", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(372, 30, "소스 재료", "케첩", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(373, 30, "소스 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(374, 30, "소스 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(375, 30, "소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(376, 30, "소스 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(377, 30, "소스 재료", "진간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(378, 30, "소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(379, 31, "기본 재료", "명엽채", "3", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(380, 31, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(381, 31, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(382, 31, "양념 재료", "간장", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(383, 31, "양념 재료", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(384, 31, "양념 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(385, 31, "양념 재료", "마요네즈", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(386, 31, "양념 재료", "식용유", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(387, 31, "양념 재료", "다진마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(388, 31, "양념 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(389, 32, "기본 재료", "삼겹살", "800", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(390, 32, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(391, 32, "기본 재료", "무", "1/6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(392, 32, "기본 재료", "반숙달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(393, 32, "기본 재료", "꽈리고추", "15", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(394, 32, "기본 재료", "연겨자", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(395, 32, "고기 삶는 물 재료", "된장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(396, 32, "고기 삶는 물 재료", "대파(파란부분)", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(397, 32, "고기 삶는 물 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(398, 32, "고기 삶는 물 재료", "통마늘", "4", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(399, 32, "고기 삶는 물 재료", "생강(마늘 1쪽 사이즈)", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(400, 32, "고기 삶는 물 재료", "통후추", "10", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(401, 32, "고기 삶는 물 재료", "월계수잎", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(402, 32, "간장 조림 재료", "물", "5", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(403, 32, "간장 조림 재료", "간장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(404, 32, "간장 조림 재료", "설탕", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(405, 32, "간장 조림 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(406, 32, "간장 조림 재료", "굴소스", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(407, 32, "간장 조림 재료", "다진마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(408, 32, "간장 조림 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(409, 33, "기본 재료", "떡볶이떡", "12", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(410, 33, "기본 재료", "비엔나소시지", "12", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(411, 33, "기본 재료", "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(412, 33, "기본 재료", "머스터드 소스", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(413, 33, "기본 재료", "나무꼬치", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(414, 33, "소스 재료", "케첩", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(415, 33, "소스 재료", "올리고당", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(416, 33, "소스 재료", "고추장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(417, 33, "소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(418, 33, "소스 재료", "간장", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(419, 33, "소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(420, 34, "기본 재료", "양배추", "1/4", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(421, 34, "기본 재료", "감자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(422, 34, "기본 재료", "식용유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(423, 34, "반죽 재료", "찹쌀가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(424, 34, "반죽 재료", "부침가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(425, 34, "반죽 재료", "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(426, 34, "반죽 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(427, 35, "기본 재료", "떡볶이떡", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(428, 35, "기본 재료", "쇠고기(불고기용)", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(429, 35, "기본 재료", "표고버섯", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(430, 35, "기본 재료", "파프리카", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(431, 35, "기본 재료", "당근", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(432, 35, "기본 재료", "참기름", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(433, 35, "기본 재료", "깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(434, 35, "떡 양념", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(435, 35, "떡 양념", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(436, 35, "떡 양념", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(437, 35, "쇠고기 양념", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(438, 35, "쇠고기 양념", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(439, 35, "쇠고기 양념", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(440, 35, "쇠고기 양념", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(441, 35, "쇠고기 양념", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(442, 36, "기본 재료", "떡볶이 떡", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(443, 36, "기본 재료", "비엔나소시지", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(444, 36, "기본 재료", "베이컨", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(445, 36, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(446, 36, "기본 재료", "넓적 당면", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(447, 36, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(448, 36, "기본 재료", "다진 마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(449, 36, "기본 재료", "파마산 치즈 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(450, 36, "양념 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(451, 36, "양념 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(452, 36, "양념 재료", "토마토소스", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(453, 36, "양념 재료", "고춧가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(454, 36, "양념 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(455, 36, "양념 재료", "카레가루", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(456, 36, "양념 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(457, 36, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(458, 37, "기본 재료", "아귀", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(459, 37, "기본 재료", "미더덕(또는 오만둥이)", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(460, 37, "기본 재료", "일자콩나물(찜용)", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(461, 37, "기본 재료", "대파", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(462, 37, "기본 재료", "미나리", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(463, 37, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(464, 37, "기본 재료", "청양고추", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(465, 37, "기본 재료", "멸치새우다시마육수", "1과1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(466, 37, "기본 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(467, 37, "기본 재료", "구운 소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(468, 37, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(469, 37, "아귀 밑간 재료", "청주", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(470, 37, "아귀 밑간 재료", "소금", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(471, 37, "양념장 재료", "고춧가루", "6", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(472, 37, "양념장 재료", "맛술", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(473, 37, "양념장 재료", "간장", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(474, 37, "양념장 재료", "참치액젓", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(475, 37, "양념장 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(476, 37, "양념장 재료", "다진 마늘", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(477, 37, "양념장 재료", "구운 소금", "1/4", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(478, 37, "양념장 재료", "생강가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(479, 37, "양념장 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(480, 37, "녹말물 재료", "녹말가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(481, 37, "녹말물 재료", "육수", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(482, 38, "기본 재료", "닭다리살", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(483, 38, "기본 재료", "고구마", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(484, 38, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(485, 38, "기본 재료", "양배추", "1/6", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(486, 38, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(487, 38, "기본 재료", "홍고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(488, 38, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(489, 38, "기본 재료", "깻잎", "5", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(490, 38, "기본 재료", "떡볶이 떡", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(491, 38, "기본 재료", "모차렐라치즈", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(492, 38, "기본 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(493, 38, "양념장", "고추장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(494, 38, "양념장", "고춧가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(495, 38, "양념장", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(496, 38, "양념장", "간장", "1과1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(497, 38, "양념장", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(498, 38, "양념장", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(499, 38, "양념장", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(500, 38, "양념장", "카레가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(501, 38, "양념장", "생강즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(502, 38, "양념장", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(503, 38, "양념장", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(504, 38, "양념장", "깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(505, 39, "기본 재료", "순대", "400", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(506, 39, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(507, 39, "기본 재료", "당근", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(508, 39, "기본 재료", "양배추", "3", "잎");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(509, 39, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(510, 39, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(511, 39, "기본 재료", "깻잎", "5", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(512, 39, "기본 재료", "들깻가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(513, 39, "기본 재료", "통깨", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(514, 39, "기본 재료", "식용유", null, "적당량");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(515, 39, "양념 소스 재료", "고추장", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(516, 39, "양념 소스 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(517, 39, "양념 소스 재료", "고춧가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(518, 39, "양념 소스 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(519, 39, "양념 소스 재료", "설탕", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(520, 39, "양념 소스 재료", "다진마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(521, 39, "양념 소스 재료", "참기름", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(522, 39, "양념 소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(523, 39, "양념 소스 재료", "물", "1/3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(524, 40, "기본 재료", "엿기름", "3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(525, 40, "기본 재료", "물", "15", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(526, 40, "기본 재료", "쌀(멥쌀)", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(527, 40, "기본 재료", "설탕", "1½", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(528, 40, "기본 재료", "생강", "1", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(529, 40, "기본 재료", "잣(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, bundleType, ingredientName, ingredientVolume, ingredientUnit) values(530, 40, "기본 재료", "대추(생략가능)", "1", "개");