insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1772, 121, "기본 재료", "파스타 면", "180", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1773, 121, "기본 재료", "달걀", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1774, 121, "기본 재료", "슬라이스 치즈", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1775, 121, "기본 재료", "올리브오일", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1776, 121, "기본 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1777, 121, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1778, 121, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1779, 121, "기본 재료", "고형 치킨스톡", "1/3", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1780, 121, "기본 재료", "면수", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1781, 121, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1782, 122, "기본 재료", "스파게티면", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1783, 122, "기본 재료", "양파", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1784, 122, "기본 재료", "마늘", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1785, 122, "기본 재료", "베이컨", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1786, 122, "기본 재료", "치킨스톡(채소스톡으로 변경 가능)", "200", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1787, 122, "기본 재료", "이태리 파슬리", "5", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1788, 122, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1789, 122, "기본 재료", "꽃소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1790, 122, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1791, 122, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1792, 122, "기본 재료", "그라나 파다노 치즈", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1793, 122, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1794, 123, "기본 재료", "스파게티 면", "160", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1795, 123, "기본 재료", "통삼겹살", "600", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1796, 123, "기본 재료", "양송이버섯", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1797, 123, "기본 재료", "아스파라거스", "4", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1798, 123, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1799, 123, "기본 재료", "마늘", "4", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1800, 123, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1801, 123, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1802, 123, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1803, 123, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1804, 123, "기본 재료", "파슬리 가루(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1805, 123, "크림소스 재료", "우유", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1806, 123, "크림소스 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1807, 123, "크림소스 재료", "파마산 치즈 가루", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1808, 123, "크림소스 재료", "치킨스톡(고형)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1809, 123, "크림소스 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1810, 123, "크림소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1811, 123, "밑간 재료", "소금", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1812, 123, "밑간 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1813, 123, "밑간 재료", "허브 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1814, 124, "기본 재료", "바지락", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1815, 124, "기본 재료", "양파", "40", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1816, 124, "기본 재료", "햄(또는 베이컨)", "60", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1817, 124, "기본 재료", "양송이버섯", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1818, 124, "기본 재료", "청양고추", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1819, 124, "기본 재료", "스파게티(또는 푸실리)", "65", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1820, 124, "기본 재료", "마늘", "5", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1821, 124, "기본 재료", "우유", "200", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1822, 124, "기본 재료", "생크림", "100", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1823, 124, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1824, 124, "기본 재료", "체다치즈", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1825, 124, "기본 재료", "파마산 치즈 가루", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1826, 124, "기본 재료", "후추", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1827, 124, "바지락 손질", "물", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1829, 124, "바지락 손질", "소금", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1829, 125, "기본 재료", "스파게티면", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1830, 125, "기본 재료", "펜네", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1831, 125, "기본 재료", "카놀라유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1832, 125, "기본 재료", "베이컨", "3", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1833, 125, "기본 재료", "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1834, 125, "기본 재료", "날치알", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1835, 125, "기본 재료", "피망", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1836, 125, "기본 재료", "대파(10cm)", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1837, 125, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1838, 125, "기본 재료", "양송이", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1839, 125, "기본 재료", "고운 고춧가루", "1/3", "술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1840, 125, "소스 재료", "휘핑크림", "100", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1841, 125, "소스 재료", "우유", "200", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1842, 125, "소스 재료", "파마산 치즈 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1843, 125, "소스 재료", "체다치즈", "4", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1844, 125, "소스 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1845, 126, "기본 재료", "스파게티면", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1846, 126, "기본 재료", "양파", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1847, 126, "기본 재료", "마늘", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1848, 126, "기본 재료", "송로오일", "2", "티스푼");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1849, 126, "기본 재료", "치킨스톡(채소스톡으로 변경 가능)", "200", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1850, 126, "기본 재료", "이태리 파슬리", "5", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1851, 126, "기본 재료", "꽃소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1852, 126, "기본 재료", "소금",  null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1853, 126, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1854, 126, "기본 재료", "그라나 파다노 치즈", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1855, 126, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1856, 127, "기본 재료", "스파게티 면", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1857, 127, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1858, 127, "기본 재료", "피망", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1859, 127, "기본 재료", "소시지", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1860, 127, "기본 재료", "올리브오일", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1861, 127, "기본 재료", "소금", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1862, 127, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1863, 127, "기본 재료", "파마산 치즈 가루(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1864, 127, "기본 재료", "다진 파슬리(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1865, 127, "소스 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1866, 127, "소스 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1867, 127, "소스 재료", "케첩", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1868, 127, "소스 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1869, 128, "기본 재료", "파스타면", "2", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1870, 128, "기본 재료", "새우", "6", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1871, 128, "기본 재료", "오징어", "1", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1872, 128, "기본 재료", "마늘", "3", "알");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1873, 128, "기본 재료", "대파", "1/2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1874, 128, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1875, 128, "기본 재료", "청경채", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1876, 128, "기본 재료", "면수", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1877, 128, "양념 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1878, 128, "양념 재료", "고춧가루", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1879, 128, "양념 재료", "식용유", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1880, 128, "양념 재료", "치킨스톡", "1/2", "큐브");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1881, 129, "기본 재료", "파스타 면", "130", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1882, 129, "기본 재료", "케일", "12", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1883, 129, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1884, 129, "기본 재료", "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1885, 129, "기본 재료", "파마산 치즈", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1886, 129, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1887, 129, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1888, 129, "크림 소스 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1889, 129, "크림 소스 재료", "치킨스톡", "2/3", "큐브");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1890, 130, "기본 재료", "스파게티", "170", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1891, 130, "기본 재료", "마늘", "6", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1892, 130, "기본 재료", "흰다리새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1893, 130, "기본 재료", "루꼴라(생략 가능)", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1894, 130, "기본 재료", "페페론치노", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1895, 130, "기본 재료", "이태리파슬리(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1896, 130, "기본 재료", "올리브오일", "5", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1897, 130, "기본 재료", "치킨스톡(고형)", "1/4", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1898, 130, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1899, 130, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1900, 131, "기본 재료", "완숙토마토", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1901, 131, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1902, 131, "기본 재료", "당근", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1903, 131, "기본 재료", "다진마늘", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1904, 131, "기본 재료", "바질가루(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1905, 131, "기본 재료", "월계수잎(생략가능)", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1906, 131, "기본 재료", "버터", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1907, 131, "기본 재료", "치킨스톡(고형)", "1", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1908, 131, "기본 재료", "물", "400", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1909, 131, "기본 재료", "파슬리(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1910, 131, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1911, 131, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1912, 131, "기본 재료", "파르메산 치즈(생략가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1913, 131, "기본 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1914, 132, "기본 재료", "사과", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1915, 132, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1916, 132, "기본 재료", "우유", "500", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1917, 132, "기본 재료", "생크림", "400", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1918, 132, "기본 재료", "타임", "5", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1919, 132, "기본 재료", "시나몬 스틱", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1920, 132, "기본 재료", "차이브", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1921, 132, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1922, 132, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1923, 132, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1924, 133, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1925, 133, "기본 재료", "감자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1926, 133, "기본 재료", "브로콜리", "1", "송이");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1927, 133, "기본 재료", "물", "2 + 1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1928, 133, "기본 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1929, 133, "기본 재료", "파마산치즈가루", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1930, 133, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1931, 133, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1932, 133, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1933, 134, "기본 재료", "소시지", "6~8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1934, 134, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1935, 134, "기본 재료", "양배추", "1/4", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1936, 134, "기본 재료", "마늘", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1937, 134, "기본 재료", "통조림 콩", "1", "병");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1938, 134, "기본 재료", "토마토소스", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1939, 134, "기본 재료", "슈레드치즈", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1940, 134, "기본 재료", "레드 와인(생략 가능)", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1941, 134, "기본 재료", "파프리카 가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1942, 134, "기본 재료", "올리브 오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1943, 134, "기본 재료", "월계수 잎", "2~3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1944, 134, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1945, 134, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1946, 134, "기본 재료", "파슬리(생략 가능)", "2", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1947, 134, "기본 재료", "물", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1948, 135, "기본 재료", "닭다리살", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1949, 135, "기본 재료", "레드와인", "1", "병");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1950, 135, "기본 재료", "샬롯", "8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1951, 135, "기본 재료", "양송이버섯", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1952, 135, "기본 재료", "통베이컨", "200", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1953, 135, "기본 재료", "토마토 페이스트", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1954, 135, "기본 재료", "버터", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1955, 135, "기본 재료", "월계수잎", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1956, 135, "기본 재료", "타임", "2", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1957, 135, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1958, 135, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1959, 136, "기본 재료", "토마토", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1960, 136, "기본 재료", "오이", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1961, 136, "기본 재료", "파프리카(빨간색)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1962, 136, "기본 재료", "샐러리", "1", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1963, 136, "기본 재료", "마늘", "1/2", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1964, 136, "기본 재료", "올리브유", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1965, 136, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1966, 136, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1967, 136, "밑간 재료", "올리브유", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1968, 136, "밑간 재료", "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1969, 136, "밑간 재료", "소금", "두", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1970, 136, "밑간 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1971, 137, "기본 재료", "옥수수", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1972, 137, "기본 재료", "감자", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1973, 137, "기본 재료", "양파", "1/3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1974, 137, "기본 재료", "우유", "3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1975, 137, "기본 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1976, 137, "기본 재료", "버터", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1977, 137, "기본 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1978, 137, "기본 재료", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1979, 137, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1980, 137, "기본 재료", "파슬리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1981, 138, "기본 재료", "모시조개", "600", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1982, 138, "기본 재료", "베이컨", "4", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1983, 138, "기본 재료", "감자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1984, 138, "기본 재료", "샐러리", "1", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1985, 138, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1986, 138, "기본 재료", "마늘", "1", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1987, 138, "기본 재료", "버터", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1988, 138, "기본 재료", "밀가루", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1989, 138, "기본 재료", "우유", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1990, 138, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1991, 138, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1992, 138, "기본 재료", "파슬리가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1993, 138, "조개 국물 재료", "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1994, 138, "조개 국물 재료", "청주", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1995, 138, "조개 국물 재료", "샐러리줄기", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1996, 138, "조개 국물 재료", "마늘", "2", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1997, 139, "기본 재료", "닭가슴살(또는 닭다리살)", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1998, 139, "기본 재료", "방울토마토", "10", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(1999, 139, "기본 재료", "양송이버섯", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2000, 139, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2001, 139, "기본 재료", "파프리카", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2002, 139, "기본 재료", "마늘", "3", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2003, 139, "기본 재료", "블랙올리브", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2004, 139, "기본 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2005, 139, "기본 재료", "건고추(또는 페페론치노 6개)", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2006, 139, "기본 재료", "파슬리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2007, 139, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2008, 139, "닭고기 밑간 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2009, 139, "닭고기 밑간 재료", "올리브유", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2010, 139, "닭고기 밑간 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2011, 139, "닭고기 밑간 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2012, 139, "닭고기 밑간 재료", "로즈마리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2013, 139, "소스 재료", "물", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2014, 139, "소스 재료", "시판 토마토소스", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2015, 139, "소스 재료", "월계수잎", "3", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2016, 139, "소스 재료", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2017, 139, "소스 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2018, 140, "기본 재료", "단호박(작은 크기)", "1", "통");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2019, 140, "기본 재료", "감자", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2020, 140, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2021, 140, "기본 재료", "버터", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2022, 140, "기본 재료", "물", "3", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2023, 140, "기본 재료", "우유", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2024, 140, "기본 재료", "생크림", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2025, 140, "기본 재료", "올리고당", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2026, 140, "기본 재료", "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2027, 140, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2028, 140, "기본 재료", "파슬리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2029, 140, "기본 재료", "휘핑 생크림", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2030, 141, "기본 재료", "바게트", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2031, 141, "기본 재료", "통마늘", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2032, 141, "기본 재료", "바질 잎", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2033, 141, "기본 재료", "선 드라이 토마토", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2034, 141, "기본 재료", "선 드라이 토마토 페이스트", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2035, 141, "기본 재료", "올리브오일", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2036, 141, "기본 재료", "리코타 치즈", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2037, 141, "기본 재료", "부라타 치즈", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2038, 141, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2039, 141, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2040, 142, "기본 재료", "에리스리톨(알룰로스 가루, 라칸토로 대체 가능)", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2041, 142, "기본 재료", "우유", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2042, 142, "기본 재료", "무염 버터", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2043, 142, "기본 재료", "달걀", "3", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2044, 142, "기본 재료", "레몬즙", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2045, 142, "기본 재료", "레몬 제스트", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2046, 142, "기본 재료", "레몬 제스트(장식용)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2047, 142, "기본 재료", "에리스리톨 파우더(아이싱용)", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2048, 142, "기본 재료", "레몬즙(아이싱용)", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2049, 142, "기본 재료", "물(아이싱용)", "20", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2050, 142, "가루 재료", "아몬드 가루", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2051, 142, "가루 재료", "코코넛 가루", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2052, 142, "가루 재료", "베이킹파우더", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2053, 142, "가루 재료", "소금", "2", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2054, 143, "기본 재료", "통밀가루", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2055, 143, "기본 재료", "아몬드가루", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2056, 143, "기본 재료", "베이킹파우더", "4", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2057, 143, "기본 재료", "소금", "1", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2058, 143, "기본 재료", "두유", "65", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2059, 143, "기본 재료", "포도씨 오일", "65", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2060, 143, "기본 재료", "황설탕", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2061, 143, "기본 재료", "다진 호두", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2062, 143, "기본 재료", "다진 피스타치오(또는 호박씨)", "40", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2063, 144, "기본 재료", "크로와상 생지", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2064, 144, "기본 재료", "달걀", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2065, 144, "기본 재료", "베이컨", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2066, 144, "기본 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2067, 144, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2068, 144, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2069, 144, "스프레드 재료", "마요네즈", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2070, 144, "스프레드 재료", "머스타드", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2071, 144, "식초물 재료", "물", "1", "리터");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2072, 144, "식초물 재료", "식초", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2073, 144, "소스 재료", "버터", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2074, 144, "소스 재료", "달걀 노른자", "2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2075, 144, "소스 재료", "물", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2076, 144, "소스 재료", "레몬즙(혹은 식초)", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2077, 144, "소스 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2078, 144, "소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2079, 145, "기본 재료", "난", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2080, 145, "기본 재료", "시금치", "4~5", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2081, 145, "기본 재료", "방울토마토", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2082, 145, "기본 재료", "양파", "1/4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2083, 145, "기본 재료", "잠봉", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2084, 145, "기본 재료", "마늘", "1/2", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2085, 145, "기본 재료", "파마산 치즈", "한", "줌");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2086, 145, "소스 재료", "그릭요거트", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2087, 145, "소스 재료", "마요네즈", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2088, 145, "소스 재료", "올리고당", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2089, 145, "소스 재료", "레몬즙", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2090, 145, "소스 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2091, 146, "기본 재료", "강력분", "450", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2092, 146, "기본 재료", "통밀가루", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2093, 146, "기본 재료", "소금", "8", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2094, 146, "기본 재료", "황설탕", "45", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2095, 146, "기본 재료", "드라이이스트(골드)", "6", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2096, 146, "기본 재료", "포도씨 오일", "25", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2097, 146, "기본 재료", "물", "265~270", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2098, 147, "기본 재료", "녹인 무염 버터", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2099, 147, "기본 재료", "우유", "60", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2100, 147, "기본 재료", "달걀", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2101, 147, "기본 재료", "잘게 썬 체다치즈", "65", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2102, 147, "기본 재료", "아몬드 가루", "220", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2103, 147, "기본 재료", "오트 파이버 가루(귀리 식이섬유)", "25", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2104, 147, "기본 재료", "파마산 치즈 가루", "45", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2105, 147, "기본 재료", "에리스리톨(알룰로스 가루, 라칸토로 대체 가능)", "18", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2106, 147, "기본 재료", "베이킹파우더", "9", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2107, 148, "기본 재료", "통밀가루", "85", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2108, 148, "기본 재료", "현미가루", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2109, 148, "기본 재료", "카카오가루", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2110, 148, "기본 재료", "베이킹파우더", "4", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2111, 148, "기본 재료", "초코칩", "40", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2112, 148, "기본 재료", "두유", "160", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2113, 148, "기본 재료", "포도씨 오일", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2114, 148, "기본 재료", "식초", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2115, 148, "기본 재료", "황설탕", "50", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2116, 148, "기본 재료", "토핑용 견과류(피스타치오, 아몬드, 캐슈넛, 피칸)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2117, 149, "기본 재료", "바나나", "90", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2118, 149, "기본 재료", "메이플 시럽", "150", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2119, 149, "기본 재료", "두유", "90", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2120, 149, "기본 재료", "포도씨 오일", "45", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2121, 149, "기본 재료", "식초", "15", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2122, 149, "기본 재료", "통밀가루", "90", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2123, 149, "기본 재료", "아몬드 가루", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2124, 149, "기본 재료", "카카오 가루", "45", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2125, 149, "기본 재료", "베이킹파우더", "6", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2126, 149, "기본 재료", "다진 초코칩", "60", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2127, 149, "기본 재료", "카라멜라이징용 황설탕", "10", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2128, 149, "장식 재료", "바나나 슬라이스(0.5cm 두께)", "9", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2129, 150, "기본 재료", "사과", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2130, 150, "기본 재료", "고르곤졸라 치즈", "30", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2131, 150, "기본 재료", "피자 치즈", "100", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2132, 150, "기본 재료", "꿀", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2133, 150, "기본 재료", "굵게 다진 호두", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2134, 150, "피자 도우 재료", "강력분", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2135, 150, "피자 도우 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2136, 150, "피자 도우 재료", "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2137, 150, "피자 도우 재료", "드라이 이스트", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2138, 150, "피자 도우 재료", "따뜻한 물", "150", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2139, 150, "피자 도우 재료", "올리브오일", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2140, 151, "기본 재료", "쌀", "80", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2141, 151, "기본 재료", "바질", "1", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2142, 151, "기본 재료", "양파", "70", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2143, 151, "기본 재료", "그라나 파다노 치즈", "4", "티스푼");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2144, 151, "기본 재료", "버터", "2", "티스푼");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2145, 151, "기본 재료", "마늘", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2146, 151, "기본 재료", "방울토마토", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2147, 151, "기본 재료", "오징어", "1/3", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2148, 151, "기본 재료", "관자", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2149, 151, "기본 재료", "새우", "5", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2150, 151, "기본 재료", "홍합", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2151, 151, "기본 재료", "화이트 와인", "100", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2152, 151, "기본 재료", "바지락", "10", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2153, 151, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2154, 151, "기본 재료", "후추", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2155, 151, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2156, 152, "기본 재료", "땅콩호박", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2157, 152, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2158, 152, "기본 재료", "베이컨", "3", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2159, 152, "기본 재료", "생크림", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2160, 152, "기본 재료", "파마산치즈가루", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2161, 152, "기본 재료", "피자치즈", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2162, 152, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2163, 152, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2164, 152, "기본 재료", "파슬리가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2165, 152, "기본 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2166, 153, "기본 재료", "불린 병아리콩", "4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2167, 153, "기본 재료", "소금", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2168, 153, "함께 갈아줄 재료", "올리브오일", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2169, 153, "함께 갈아줄 재료", "참깨", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2170, 153, "함께 갈아줄 재료", "레몬즙", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2171, 153, "함께 갈아줄 재료", "마늘", "2", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2172, 153, "함께 갈아줄 재료", "볶은 아몬드", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2173, 153, "함께 갈아줄 재료", "커민", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2174, 153, "함께 갈아줄 재료", "소금", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2175, 153, "함께 갈아줄 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2176, 153, "가니시 재료", "방울토마토", "8", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2177, 153, "가니시 재료", "올리브", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2178, 153, "가니시 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2179, 153, "가니시 재료", "파슬리", "3~4", "줄기");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2180, 153, "가니시 재료", "삶은 병아리콩", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2181, 153, "가니시 재료", "키드니빈", null "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2182, 153, "가니시 재료", "파프리카 파우더(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2183, 153, "가니시 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2184, 154, "기본 재료", "굴", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2185, 154, "기본 재료", "통마늘", "20", "쪽");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2186, 154, "기본 재료", "브로콜리", "1/4", "송이");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2187, 154, "기본 재료", "양송이버섯", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2188, 154, "기본 재료", "방울토마토", "5", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2189, 154, "기본 재료", "페페론치노", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2190, 154, "기본 재료", "바질 페스토", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2191, 154, "기본 재료", "올리브오일", "1", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2192, 154, "기본 재료", "소금", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2193, 154, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2194, 154, "기본 재료", "타임(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2195, 154, "기본 재료", "바게트 빵 또는 스파게티면(생략 가능)", "2~3", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2196, 155, "기본 재료", "돼지고기(앞다리살)", "1.2", "kg");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2197, 155, "기본 재료", "바베큐소스", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2198, 155, "밑간 재료", "스테이크 시즈닝(또는 허브솔트)", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2199, 155, "밑간 재료", "꿀(또는 올리고당)", "4", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2200, 156, "기본 재료", "감자", "4", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2201, 156, "기본 재료", "까망베르 치즈", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2202, 156, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2203, 156, "기본 재료", "두꺼운 베이컨", "1/2", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2204, 156, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2205, 156, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2206, 156, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2207, 156, "기본 재료", "파슬리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2208, 157, "기본 재료", "쇠고기 사태", "500", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2209, 157, "기본 재료", "두꺼운 베이컨", "2", "줄");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2210, 157, "기본 재료", "당근", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2211, 157, "기본 재료", "샐러리", "2", "대");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2212, 157, "기본 재료", "양송이버섯", "6", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2213, 157, "기본 재료", "통마늘", "4", "톨");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2214, 157, "기본 재료", "양파", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2215, 157, "기본 재료", "파슬리", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2216, 157, "기본 재료", "올리브오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2217, 157, "기본 재료", "버터", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2218, 157, "기본 재료", "레드 와인", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2219, 157, "기본 재료", "치킨스톡(고형)", "1/2", "조각");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2220, 157, "기본 재료", "물", "250", "ml");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2221, 157, "기본 재료", "토마토 페이스트", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2222, 157, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2223, 157, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2224, 157, "기본 재료", "월계수 잎(생략 가능)", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2225, 158, "기본 재료", "토르티야", "2", "장");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2226, 158, "기본 재료", "닭다리살", "300", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2227, 158, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2228, 158, "기본 재료", "파프리카(빨/노)", "1/2", "개씩");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2229, 158, "기본 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2230, 158, "기본 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2231, 158, "기본 재료", "큐민 가루", "1/2", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2232, 158, "기본 재료", "체다(+모차렐라 슈레드)치즈", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2233, 158, "기본 재료", "올리브유", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2234, 158, "과카몰리 재료", "아보카도", "1", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2235, 158, "과카몰리 재료", "토마토", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2236, 158, "과카몰리 재료", "라임즙", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2237, 158, "과카몰리 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2238, 158, "과카몰리 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2239, 158, "과카몰리 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2240, 158, "과카몰리 재료", "파슬리 가루(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2241, 158, "과카몰리 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2242, 158, "닭다리살 소스 재료", "간장", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2243, 158, "닭다리살 소스 재료", "맛술", "2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2244, 158, "닭다리살 소스 재료", "굴소스", "1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2245, 158, "닭다리살 소스 재료", "스리라차 소스", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2246, 158, "닭다리살 소스 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2247, 158, "닭다리살 소스 재료", "설탕", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2248, 158, "닭다리살 소스 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2249, 159, "기본 재료", "오징어", "2", "마리");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2250, 159, "기본 재료", "불린 쌀", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2251, 159, "기본 재료", "멸치 다시마 육수(물로 대체 가능)", "3~4", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2252, 159, "기본 재료", "다진 마늘", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2253, 159, "기본 재료", "청주", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2254, 159, "기본 재료", "다진 파슬리(생략 가능)", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2255, 159, "기본 재료", "레몬(생략 가능)", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2256, 159, "기본 재료", "올리브 오일", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2257, 159, "양념 재료", "파프리카 가루 (고운 고춧가루로 대체 가능)", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2258, 159, "양념 재료", "토마토소스", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2259, 159, "양념 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2260, 159, "양념 재료", "후춧가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2261, 159, "양념 재료", "카레 가루", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2262, 160, "기본 재료", "닭고기(다리살)", "400", "g");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2263, 160, "기본 재료", "양파", "1/2", "개");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2264, 160, "기본 재료", "홀토마토", "1/2", "캔");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2265, 160, "기본 재료", "시판 고형카레", "2", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2266, 160, "기본 재료", "치킨육수(또는 물)", "2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2267, 160, "기본 재료", "우유", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2268, 160, "기본 재료", "생크림", "1/2", "컵");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2269, 160, "기본 재료", "땅콩버터", "1 + 1/2", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2270, 160, "기본 재료", "버터", "3", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2271, 160, "기본 재료", "밥", "2", "인분");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2272, 160, "기본 재료", "파슬리 가루", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2273, 160, "밑간 재료", "맛술", "1", "큰술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2274, 160, "밑간 재료", "다진 마늘", "1", "작은술");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2275, 160, "밑간 재료", "생강가루", "한", "꼬집");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2276, 160, "밑간 재료", "소금", null, "약간");
insert into recipeIngredient(recipeIngredientId, recipeId, ingredientName, ingredientVolume, ingredientUnit) values(2277, 160, "밑간 재료", "후춧가루", null, "약간");